language: rust
rust:
    - stable
script:
    - cargo build --verbose --all
    - cargo test --verbose --tests
    - cargo doc --target-dir ./docs
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: docs
